/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MetodeRouteImport } from './routes/metode'
import { Route as ProRouteImport } from './routes/pro'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as KommuneSlugRouteImport } from './routes/kommune.$slug'
import { Route as OrganKeyRouteImport } from './routes/organ.$key'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MetodeRoute = MetodeRouteImport.update({
  id: '/metode',
  path: '/metode',
  getParentRoute: () => rootRouteImport,
} as any)
const ProRoute = ProRouteImport.update({
  id: '/pro',
  path: '/pro',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const KommuneSlugRoute = KommuneSlugRouteImport.update({
  id: '/kommune/$slug',
  path: '/kommune/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganKeyRoute = OrganKeyRouteImport.update({
  id: '/organ/$key',
  path: '/organ/$key',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/metode': typeof MetodeRoute
  '/pro': typeof ProRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/kommune/$slug': typeof KommuneSlugRoute
  '/organ/$key': typeof OrganKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/metode': typeof MetodeRoute
  '/pro': typeof ProRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/kommune/$slug': typeof KommuneSlugRoute
  '/organ/$key': typeof OrganKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/metode': typeof MetodeRoute
  '/pro': typeof ProRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/kommune/$slug': typeof KommuneSlugRoute
  '/organ/$key': typeof OrganKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/metode'
    | '/pro'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/kommune/$slug'
    | '/organ/$key'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/metode'
    | '/pro'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/kommune/$slug'
    | '/organ/$key'
  id:
    | '__root__'
    | '/'
    | '/metode'
    | '/pro'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/kommune/$slug'
    | '/organ/$key'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MetodeRoute: typeof MetodeRoute
  ProRoute: typeof ProRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  KommuneSlugRoute: typeof KommuneSlugRoute
  OrganKeyRoute: typeof OrganKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metode': {
      id: '/metode'
      path: '/metode'
      fullPath: '/metode'
      preLoaderRoute: typeof MetodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro': {
      id: '/pro'
      path: '/pro'
      fullPath: '/pro'
      preLoaderRoute: typeof ProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kommune/$slug': {
      id: '/kommune/$slug'
      path: '/kommune/$slug'
      fullPath: '/kommune/$slug'
      preLoaderRoute: typeof KommuneSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organ/$key': {
      id: '/organ/$key'
      path: '/organ/$key'
      fullPath: '/organ/$key'
      preLoaderRoute: typeof OrganKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MetodeRoute: MetodeRoute,
  ProRoute: ProRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  KommuneSlugRoute: KommuneSlugRoute,
  OrganKeyRoute: OrganKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
